
py_binary(
    name = "training_loop",
    srcs = ["training_loop.py"],
    deps = ["//py_alphago/py_mcts:py_mcts"],
)

py_binary(
    name = "user_ui",
    srcs = ["user_ui.py"],
    deps = ["//py_alphago/py_mcts:py_mcts"],
)
