
py_binary(
    name = "training_loop",
    srcs = ["training_loop.py"],
    deps = ["//code/py_alphago/py_mcts:py_mcts"],
)

py_binary(
    name = "user_ui",
    srcs = ["user_ui.py"],
    deps = ["//code/py_alphago/py_mcts:py_mcts"],
)

py_binary(
    name = "play_games",
    srcs = ["play_games.py"],
    deps = ["//code/py_alphago/py_mcts:py_mcts"],
)

py_binary(
    name = "train_network",
    srcs = ["train_network.py"],
    deps = ["//code/py_alphago/py_mcts:py_mcts"],
)
