
cc_library(
    name = "game",
    hdrs = ["game.h", "strategy.h"],
    srcs = ["game.cpp"],
    deps = ["//code/cpp_mcts/board:board",],
    visibility = ["//code/cpp_mcts:__subpackages__"],
)
